apiVersion: v1
kind: Pod
metadata:
  name: busybox-2.1
spec:
  containers:
  - image: busybox
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
    name: busybox
  restartPolicy: Always
  nodeSelector:
    n: "2"
